//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.TblCourse_Faculty = new HashSet<TblCourse_Faculty>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
    
        public virtual ICollection<TblCourse_Faculty> TblCourse_Faculty { get; set; }
    }
}
