//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleEntities1 : DbContext
    {
        public SampleEntities1()
            : base("name=SampleEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cours> Courses { get; set; }
        public DbSet<LogIn> LogIns { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentTransaction> StudentTransactions { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TblCourse_Faculty> TblCourse_Faculty { get; set; }
        public DbSet<TblCustomer> TblCustomers { get; set; }
        public DbSet<TblCustomerOrder> TblCustomerOrders { get; set; }
        public DbSet<TblProduct> TblProducts { get; set; }
        public DbSet<TblProductCategory> TblProductCategories { get; set; }
        public DbSet<TblProductOrder> TblProductOrders { get; set; }
        public DbSet<TblProductSubcategory> TblProductSubcategories { get; set; }
    }
}
