//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> StudntId { get; set; }
        public Nullable<int> CourseFacultyId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
