//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomerOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PaymentMethod { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> DateOrderPlaced { get; set; }
        public Nullable<System.DateTime> DateOrderPaid { get; set; }
        public Nullable<decimal> TotalOrderPrice { get; set; }
        public string OrderDescription { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
    }
}
