//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductOrder
    {
        public int TransactionKey { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> OrderDateKey { get; set; }
        public Nullable<int> CustomerKey { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblProduct TblProduct1 { get; set; }
    }
}
