//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductSubcategory
    {
        public TblProductSubcategory()
        {
            this.TblProducts = new HashSet<TblProduct>();
        }
    
        public int ProductSubcategoryID { get; set; }
        public string ProductSubcategoryLabel { get; set; }
        public string ProductSubcategoryName { get; set; }
        public string ProductSubcategoryDescription { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<TblProduct> TblProducts { get; set; }
        public virtual TblProductCategory TblProductCategory { get; set; }
    }
}
