//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_CSS_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductCategory
    {
        public TblProductCategory()
        {
            this.TblProductSubcategories = new HashSet<TblProductSubcategory>();
        }
    
        public int ProductCategoryID { get; set; }
        public string ProductCategoryLabel { get; set; }
        public string ProductCategoryName { get; set; }
        public string ProductCategoryDescription { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<TblProductSubcategory> TblProductSubcategories { get; set; }
    }
}
